#!/usr/bin/env node
// Copies deploy/docker/compose.edge.yaml and deploy/docker/Caddyfile into
// apps/cli/src/server-edge-files.ts, so the published CLI carries the TLS edge it installs with
// `mend server setup --edge <host>`. The repository files stay the source; server-edge.test.ts
// fails when this copy drifts from them. Run: node apps/cli/scripts/edge-files.mjs
import { readFileSync, writeFileSync } from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const source = (name) => readFileSync(path.join(root, "deploy", "docker", name), "utf8");
const literal = (text) =>
  `[\n${text
    .replace(/\n$/, "")
    .split("\n")
    .map((line) => `  ${JSON.stringify(line)},`)
    .join("\n")}\n].join("\\n") + "\\n"`;

const module = `// Generated by apps/cli/scripts/edge-files.mjs from deploy/docker; do not edit by hand.
// The TLS edge a packaged install runs when an edge host is set (docs/adr/0004).

/** deploy/docker/compose.edge.yaml, byte for byte. */
export const EDGE_COMPOSE_OVERLAY: string = ${literal(source("compose.edge.yaml"))};

/** deploy/docker/Caddyfile, byte for byte. */
export const EDGE_CADDYFILE: string = ${literal(source("Caddyfile"))};
`;

writeFileSync(path.join(root, "apps", "cli", "src", "server-edge-files.ts"), module);
