#!/usr/bin/env node
// A full Mend stack built from source inside one Docker daemon, normally a Mend session's own:
// sealantd, Sealant Core (API, worker, SSH gateway) and Mend, each at a ref, installed with the
// product's own `mend server setup`, so a verifier can drive a change that spans the three
// repositories. docs/operations/verify-stack.md says how to use it; mend.toml declares it as the
// `stack` Service.
//
//   node scripts/verify-stack/stack.mjs up [sources] [--port <n>] [--no-check]
//   node scripts/verify-stack/stack.mjs serve [sources] [--port <n>]   up, then hold; down on exit
//   node scripts/verify-stack/stack.mjs mend <args…>                     the inner CLI
//   node scripts/verify-stack/stack.mjs check                           inner mend run -- true
//   node scripts/verify-stack/stack.mjs report [--json]                 sources, timings, memory
//   node scripts/verify-stack/stack.mjs down [--purge]                  remove the stack
//
// Sources: --mend, --sealant, --sealantd, each a path (a working tree as it is), #<pr>, a branch,
// tag or commit on GitHub, or `pinned` (Core and sealantd: the release Mend pins, no build).
// Defaults: this checkout for Mend; /workspace/repos/<name> when `mend repo add` brought it into
// the session, else main.
//
// What it never does: put a secret in argv, a log or a capture root. The inner server's secrets
// are generated by `mend server setup` inside a container and live in a Docker volume of this
// daemon; its first account's password and token are written there too. Docker clients run with
// an environment of their own (lib.mjs dockerClientEnvironment): no MEND_* variable of the session
// reaches them, so nothing of the stack holds a credential of the outer server.

import { spawn } from "node:child_process";
import { randomBytes, randomUUID } from "node:crypto";
import {
  closeSync,
  constants,
  createWriteStream,
  existsSync,
  fstatSync,
  lstatSync,
  mkdirSync,
  openSync,
  readFileSync,
} from "node:fs";
import { lstat, mkdir, readFile, readdir, rename, rm, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  COMPOSE_NETWORK,
  COMPOSE_PROJECT,
  DOCKER_CLI_IMAGE,
  FIXTURE_BASE_IMAGE,
  FIXTURE_CONTAINER,
  FIXTURE_PROJECT,
  FIXTURE_VOLUME,
  INNER_ACCOUNT_EMAIL,
  INNER_WEB_PORT,
  MEMORY_PROBE,
  REPOSITORIES,
  RELAY_CONTAINER,
  SESSION_REPOS,
  STACK_LABEL,
  STATE_VOLUME,
  VERIFIER_PREFIX,
  beyondRetention,
  composeImages,
  defaultSpec,
  describeSource,
  digestOf,
  dockerClientEnvironment,
  fetchRefspec,
  formatKb,
  formatSeconds,
  SHAPES,
  madeSince,
  manualRemoval,
  mergeLedgers,
  planTeardown,
  imageNames,
  innerOrigins,
  insideCaptureRoot,
  isolationFindings,
  mendBuildArgs,
  parseMemory,
  parseSource,
  relayEndpoint,
} from "./lib.mjs";
import {
  claim,
  currentClaim,
  sendSafely,
  settleClaim,
  teardownGeneration,
  watch,
} from "./lifecycle.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const mendRoot = resolve(here, "../..");
const cacheDir = resolve(
  process.env.MEND_VERIFY_STACK_CACHE ??
    join(process.env.XDG_CACHE_HOME || join(homedir(), ".cache"), "mend-verify-stack"),
);
const stateFile = join(cacheDir, "stack.json");
const dockerEnv = dockerClientEnvironment(process.env, {
  home: join(cacheDir, "home"),
  dockerConfig: join(cacheDir, "docker-config"),
});
// What the outer session holds that the inner stack must never see; checked, never printed. A
// shared-layout session carries its token in the environment; a per-person one (docs/adr/0016)
// in `~/.mend/session-token`, or the file MEND_SESSION_TOKEN_FILE names.
const outerSecrets = (() => {
  const values = Object.entries(process.env)
    .filter(([key]) => /^(MEND_SESSION_TOKEN|SEALANT_CAPTURE_TOKEN|MEND_TOKEN)$/.test(key))
    .map(([, value]) => value);
  for (const file of [process.env.MEND_SESSION_TOKEN_FILE, join(homedir(), ".mend/session-token")])
    if (file) {
      try {
        values.push(readFileSync(file, "utf8").trim());
      } catch {
        // Absent outside a session, or not this person's.
      }
    }
  return [...new Set(values.filter((value) => value.length > 0))];
})();

// ─── processes ──────────────────────────────────────────────────────────────

class CommandError extends Error {}

/**
 * The daemon's lock (`lockDaemon`): this process's descriptor of the lock file, open once the lock
 * is taken, and the position it takes in a child's stdio. Every command of a holder's that may change
 * the stack gets it there (`holdsLock`), so the lock stays held until the last of them has exited,
 * even if this process is killed first: a removal still in flight keeps blocking admission.
 */
let lockFd = null;
const LOCK_FD = 9;

function stdioFor(stdio, input, lock) {
  const base = stdio ?? [input === undefined ? "ignore" : "pipe", "pipe", "pipe"];
  if (!lock || lockFd === null || !Array.isArray(base)) return base;
  const withLock = [...base];
  while (withLock.length < LOCK_FD) withLock.push("ignore");
  withLock[LOCK_FD] = lockFd;
  return withLock;
}

/**
 * Whether a command carries the daemon's lock: `flock` (it takes it) and every Docker command that
 * may change the stack's containers, volumes or networks. One that only reads or fetches (a pull, a
 * build, an inspect) does not, so one left running by a holder that ended (a stalled pull) never
 * keeps the lock from the teardown that follows.
 */
const READ_ONLY_DOCKER = new Set([
  "build",
  "buildx",
  "image",
  "info",
  "inspect",
  "ps",
  "pull",
  "stats",
  "version",
]);
function holdsLock(command, [verb, sub] = []) {
  if (command === "flock") return true;
  if (command !== "docker") return false;
  if (READ_ONLY_DOCKER.has(verb)) return false;
  if ((verb === "volume" || verb === "network") && (sub === "ls" || sub === "inspect"))
    return false;
  return true;
}

/**
 * Run a command. Output is captured, or appended to `log` when given (builds); `input` is written
 * to stdin. A failure names the command and its exit; its output is printed only for `log`ged
 * commands, which carry no secret (a build log), as the last lines of that log.
 */
function exec(command, args, options = {}) {
  const { env = dockerEnv, cwd, input, log, timeout = 30 * 60_000, stdio, reason } = options;
  const lock = holdsLock(command, args);
  return new Promise((resolvePromise, reject) => {
    const child = spawn(command, args, { cwd, env, stdio: stdioFor(stdio, input, lock) });
    const out = [];
    const err = [];
    const sink = log ? createWriteStream(log, { flags: "a" }) : null;
    child.stdout?.on("data", (chunk) => (sink ? sink.write(chunk) : out.push(chunk)));
    child.stderr?.on("data", (chunk) => (sink ? sink.write(chunk) : err.push(chunk)));
    const timer = setTimeout(() => child.kill("SIGKILL"), timeout);
    child.once("error", (error) => {
      clearTimeout(timer);
      reject(new CommandError(`${command} could not start: ${error.message}`));
    });
    child.once("close", async (code, signal) => {
      clearTimeout(timer);
      if (sink) await new Promise((done) => sink.end(done));
      const stdout = Buffer.concat(out).toString();
      const stderr = Buffer.concat(err).toString();
      if (code === 0) return resolvePromise({ stdout, stderr });
      let tail = "";
      if (log) {
        const lines = (await readFile(log, "utf8").catch(() => "")).trimEnd().split("\n");
        tail = `\n${lines.slice(-30).join("\n")}\n(full log: ${log})`;
      }
      const ended = signal ? `signal ${signal}` : `exit ${code}`;
      // The verb, not a flag or a path; and, when the caller asks, the command's own last word on
      // why (only for commands whose output carries no secret, such as an anonymous fetch).
      const verb = args.find((arg) => !arg.startsWith("-") && !arg.startsWith("/")) ?? "";
      const why = reason ? `: ${stderr.trim().split("\n").at(-1) ?? ""}` : "";
      reject(new CommandError(`${command} ${verb} failed (${ended})${why}${tail}`));
    });
    if (input !== undefined) child.stdin.end(input);
  });
}

const docker = (args, options) => exec("docker", args, options);
const dockerOut = async (args, options) => (await docker(args, options)).stdout.trim();
const git = (repo, args, options = {}) =>
  exec("git", ["-C", repo, ...args], { env: options.env ?? process.env, ...options });
const gitOut = async (repo, args, options) => (await git(repo, args, options)).stdout.trim();

const say = (line) => process.stdout.write(`${line}\n`);
const since = (start) => (Date.now() - start) / 1000;
const pause = (ms) => new Promise((done) => setTimeout(done, ms));

/**
 * The name and label of a container the stack runs for a moment (a copy, a probe, the inner CLI):
 * both, so a teardown finds one a killed command left behind (lib.mjs `planTeardown`).
 */
const transient = (purpose) => [
  "--name",
  `${VERIFIER_PREFIX}${purpose}-${randomUUID().slice(0, 8)}`,
  "--label",
  `${STACK_LABEL}=1`,
];

async function timed(record, name, work) {
  const start = Date.now();
  const result = await work();
  record[name] = Math.round(since(start) * 10) / 10;
  return result;
}

// ─── sources ────────────────────────────────────────────────────────────────

async function sessionRepos() {
  try {
    return await readdir(SESSION_REPOS);
  } catch {
    return [];
  }
}

/** The commit and tree a source names, and where git can archive the tree from. */
async function resolveSource(source) {
  if (source.kind === "pinned") return source;
  if (source.kind === "worktree") {
    const path = resolve(source.path.replace(/^~(?=\/)/, homedir()));
    const root = await gitOut(path, ["rev-parse", "--show-toplevel"]);
    const commit = await gitOut(root, ["rev-parse", "HEAD"]);
    // The working tree as a tree object, through a private index: the person's index, branch and
    // files are not touched. Untracked files count unless ignored, as `git status` shows them.
    const index = join(cacheDir, `index-${randomUUID()}`);
    const env = { ...process.env, GIT_INDEX_FILE: index };
    try {
      await git(root, ["read-tree", "HEAD"], { env });
      await git(root, ["add", "--all", "--", "."], { env });
      const tree = await gitOut(root, ["write-tree"], { env });
      const headTree = await gitOut(root, ["rev-parse", "HEAD^{tree}"]);
      return { ...source, path: root, gitDir: root, commit, tree, dirty: tree !== headTree };
    } finally {
      await rm(index, { force: true });
    }
  }
  const gitDir = join(cacheDir, "git", `${source.repository}.git`);
  if (!existsSync(join(gitDir, "HEAD"))) {
    await mkdir(gitDir, { recursive: true });
    await git(gitDir, ["init", "--bare", "--quiet"], { env: dockerEnv });
  }
  const { url } = REPOSITORIES[source.repository];
  // Into a ref of this fetch's own, not FETCH_HEAD: two starts sharing the cache each read back
  // the commit they fetched.
  const ref = `refs/verify-stack/${randomUUID()}`;
  await git(
    gitDir,
    ["fetch", "--quiet", "--no-tags", "--depth", "1", url, `+${fetchRefspec(source)}:${ref}`],
    { env: dockerEnv, timeout: 10 * 60_000, reason: true },
  ).catch((error) => {
    throw new CommandError(
      `--${source.repository} ${source.kind === "pr" ? `#${source.number}` : source.ref}: ${url} would not give it (${error.message})`,
    );
  });
  const commit = await gitOut(gitDir, ["rev-parse", ref], { env: dockerEnv });
  const tree = await gitOut(gitDir, ["rev-parse", `${ref}^{tree}`], { env: dockerEnv });
  return { ...source, gitDir, commit, tree };
}

/** The source tree as a directory, made once per tree: every build of it uses this context. */
async function contextOf(resolved) {
  const dir = join(cacheDir, "contexts", `${resolved.repository}-${resolved.tree}`);
  if (existsSync(dir)) return dir;
  const partial = `${dir}.partial-${randomUUID()}`;
  await mkdir(partial, { recursive: true });
  await new Promise((done, fail) => {
    const archive = spawn(
      "git",
      ["-C", resolved.gitDir, "archive", "--format=tar", resolved.tree],
      {
        env: process.env,
        stdio: ["ignore", "pipe", "inherit"],
      },
    );
    const untar = spawn("tar", ["-x", "-C", partial], { stdio: ["pipe", "inherit", "inherit"] });
    archive.stdout.pipe(untar.stdin);
    let pending = 2;
    const settle = (name) => (code) => {
      if (code !== 0) fail(new CommandError(`${name} of ${resolved.repository} failed (${code})`));
      else if (--pending === 0) done();
    };
    archive.once("close", settle("git archive"));
    untar.once("close", settle("tar"));
  });
  await rename(partial, dir);
  return dir;
}

const showFile = (resolved, path) =>
  gitOut(resolved.gitDir, ["show", `${resolved.tree}:${path}`], { env: process.env });

// ─── images ─────────────────────────────────────────────────────────────────

const imageId = (tag) =>
  dockerOut(["image", "inspect", "--format", "{{.Id}}", tag]).catch(() => null);

/**
 * Build one image unless this daemon already holds it under its tag (the same tree was built
 * before). `dockerfile` is a path in the context, or `{ text }` for a Dockerfile the stack owns.
 */
async function build(logs, name, { context, dockerfile, tag, args = {}, labels = {} }) {
  if (await imageId(tag)) return "reused";
  const log = join(logs, `${name}.log`);
  const argv = ["build", "--tag", tag, "--label", `${STACK_LABEL}=1`];
  for (const [key, value] of Object.entries(labels)) argv.push("--label", `${key}=${value}`);
  for (const [key, value] of Object.entries(args)) argv.push("--build-arg", `${key}=${value}`);
  const text = typeof dockerfile === "string" ? undefined : dockerfile.text;
  argv.push("--file", text === undefined ? join(context, dockerfile) : "-", context);
  await docker(argv, { log, input: text });
  return "built";
}

/** Where the inner CLI image carries deploy/docker, the assets `mend server setup` installs. */
const ASSETS_DIR = "/opt/mend-assets";

/**
 * The inner CLI: the `@sealant/mend` package packed from this Mend source and installed with npm,
 * as a person installs a release, beside the Docker CLI and Compose plugin setup drives. Its first
 * stage repeats the bundle's build stage word for word, so their install is one cached layer.
 */
const CLI_DOCKERFILE = `
FROM ${DOCKER_CLI_IMAGE} AS docker-cli

FROM node:26-bookworm-slim AS mend-build
ENV PNPM_HOME=/pnpm PATH=/pnpm:$PATH COREPACK_ENABLE_DOWNLOAD_PROMPT=0
RUN npm install --global corepack && corepack enable
WORKDIR /app
COPY . .
RUN pnpm install --frozen-lockfile
RUN mkdir /pack && cd apps/cli && pnpm pack --pack-destination /pack

FROM node:26-bookworm-slim
RUN apt-get update \\
  && apt-get install -y --no-install-recommends ca-certificates git openssh-client \\
  && rm -rf /var/lib/apt/lists/*
COPY --from=mend-build /pack /pack
RUN npm install --global --no-audit --no-fund /pack/*.tgz && rm -rf /pack
COPY --from=docker-cli /usr/local/bin/docker /usr/local/bin/docker
COPY --from=docker-cli /usr/local/libexec/docker/cli-plugins/docker-compose /usr/local/libexec/docker/cli-plugins/docker-compose
# The release assets of this same source: setup copies them into the generation it writes.
COPY deploy/docker ${ASSETS_DIR}
ENTRYPOINT ["mend"]
`;

/**
 * BuildKit's client, the buildx plugin, in the stack's own Docker configuration when this Docker
 * CLI lacks it: a session's workspace image carries the CLI and Compose only (PLATFORM-FEEDBACK.md
 * 2026-10-10), and the Dockerfiles built here need BuildKit. Copied out of the CLI image the
 * bundle's worker uses, over the daemon's API, for the daemon's platform.
 */
async function ensureBuildx() {
  if (
    await docker(["buildx", "version"]).then(
      () => true,
      () => false,
    )
  )
    return;
  const plugins = join(dockerEnv.DOCKER_CONFIG, "cli-plugins");
  await mkdir(plugins, { recursive: true, mode: 0o700 });
  await docker(["pull", "--quiet", DOCKER_CLI_IMAGE], { timeout: 15 * 60_000 });
  const id = await dockerOut(["create", ...transient("buildx"), DOCKER_CLI_IMAGE]);
  try {
    await docker([
      "cp",
      `${id}:/usr/local/libexec/docker/cli-plugins/docker-buildx`,
      join(plugins, "docker-buildx"),
    ]);
  } finally {
    await docker(["rm", "--force", id]);
  }
  await docker(["buildx", "version"]);
  say("  buildx · copied from " + DOCKER_CLI_IMAGE + " (this Docker CLI has none)");
}

// ─── the stack's state ──────────────────────────────────────────────────────

const readState = async () => {
  try {
    return JSON.parse(await readFile(stateFile, "utf8"));
  } catch {
    return null;
  }
};
const writeState = async (state) => {
  await mkdir(cacheDir, { recursive: true, mode: 0o700 });
  await writeFile(stateFile, `${JSON.stringify(state, null, 2)}\n`, { mode: 0o600 });
};

/** The state volume's path as the daemon sees it: bind sources under it exist for the daemon. */
const stateMount = () =>
  dockerOut(["volume", "inspect", "--format", "{{.Mountpoint}}", STATE_VOLUME]);

/**
 * `docker run` of the inner CLI: its server and client homes in the state volume. It runs in the
 * daemon's host network, where the relay's port answers on loopback (published there, or by a
 * rootless daemon's proxy), so it speaks to the server at the browser's URL and every link it
 * prints (a session, an invitation) opens on the machine that ran `mend service connect`.
 */
async function cliRun(state, args, { network = "host", home = "client", ...options } = {}) {
  const mount = await stateMount();
  const interactive = options.stdio === "inherit" && process.stdin.isTTY ? ["-t"] : [];
  return docker(
    [
      "run",
      "--rm",
      "-i",
      ...interactive,
      ...transient("cli"),
      "--network",
      network,
      "--volume",
      `${STATE_VOLUME}:${mount}`,
      "--env",
      `HOME=${mount}/${home}`,
      "--env",
      `XDG_CONFIG_HOME=${mount}/${home}/.config`,
      ...(home === "server"
        ? ["--volume", `${state.dockerSocket}:/var/run/docker.sock`, "--env", "NO_COLOR=1"]
        : []),
      state.images.cli,
      ...args,
    ],
    options,
  );
}

/**
 * Write a private file into the state volume, whole or not at all (written aside, then renamed); its
 * content goes over stdin, never argv.
 */
async function writePrivate(state, path, content) {
  const mount = await stateMount();
  await docker(
    [
      "run",
      "--rm",
      "-i",
      ...transient("write"),
      "--network",
      "none",
      "--volume",
      `${STATE_VOLUME}:${mount}`,
      "--entrypoint",
      "sh",
      state.images.cli,
      "-c",
      'umask 077 && mkdir -p "$(dirname "$1")" && cat > "$1.tmp" && mv -f "$1.tmp" "$1"',
      "sh",
      `${mount}/${path}`,
    ],
    { input: content },
  );
}

async function readPrivate(state, path) {
  const mount = await stateMount();
  return dockerOut([
    "run",
    "--rm",
    ...transient("read"),
    "--network",
    "none",
    "--volume",
    `${STATE_VOLUME}:${mount}:ro`,
    "--entrypoint",
    "cat",
    state.images.cli,
    `${mount}/${path}`,
  ]);
}

/** The daemon-side path of its own socket, which the inner Mend container mounts. */
async function daemonSocket() {
  const info = JSON.parse(await dockerOut(["info", "--format", "{{json .}}"]));
  const rootless = (info.SecurityOptions ?? []).some((option) => option.includes("rootless"));
  // A rootless daemon (a session's sidecar) listens at $XDG_RUNTIME_DIR/docker.sock of its user;
  // its runtime directory is the daemon's own `/run/user/<uid>`.
  if (rootless) {
    const runtime = await dockerOut([
      "run",
      "--rm",
      ...transient("socket"),
      "--network",
      "none",
      "--volume",
      "/run/user:/host-run-user:ro",
      "--entrypoint",
      "sh",
      FIXTURE_BASE_IMAGE,
      "-c",
      "ls /host-run-user/*/docker.sock",
    ]);
    const socket = runtime.split("\n")[0]?.replace("/host-run-user", "/run/user");
    if (!socket)
      throw new CommandError("the rootless daemon's socket was not found under /run/user");
    return { rootless, socket };
  }
  return { rootless, socket: "/var/run/docker.sock" };
}

// ─── up ─────────────────────────────────────────────────────────────────────

/**
 * The relay's port, and so the browser origin's: not 3105, where Mend's own dev server listens when
 * a session runs `pnpm dev` (apps/web/vite.config.ts), since Mend dials the workspace loopback
 * before the Docker sidecar.
 */
const DEFAULT_PORT = 3305;

/** The inner server publishes its web port this far above the relay's. */
const SERVER_PORT_OFFSET = 10_000;

function parseFlags(args) {
  const flags = {
    port: DEFAULT_PORT,
    check: true,
    json: false,
    purge: false,
    force: false,
    keep: false,
  };
  const sources = {};
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    const value = () => {
      if (i + 1 >= args.length) throw new Error(`${arg} needs a value`);
      return args[++i];
    };
    if (arg === "--mend" || arg === "--sealant" || arg === "--sealantd")
      sources[arg.slice(2)] = value();
    else if (arg === "--port") flags.port = Number(value());
    else if (arg === "--no-check") flags.check = false;
    else if (arg === "--json") flags.json = true;
    else if (arg === "--purge") flags.purge = true;
    else if (arg === "--force") flags.force = true;
    else if (arg === "--keep") flags.keep = true;
    else throw new Error(`unknown option ${arg}`);
  }
  if (!Number.isInteger(flags.port) || flags.port < 1024 || flags.port + SERVER_PORT_OFFSET > 65535)
    throw new Error(`--port takes a port between 1024 and ${65535 - SERVER_PORT_OFFSET}`);
  return { flags, sources };
}

/** Refuse a daemon that runs a Mend server the stack did not make: its names are the same. */
async function assertDaemonIsFree() {
  const volumes = (await dockerOut(["volume", "ls", "--quiet"])).split("\n").filter(Boolean);
  const product = ["mend-store", "mend-control", "mend-garage"].filter((v) => volumes.includes(v));
  const compose = await dockerOut([
    "ps",
    "--all",
    "--quiet",
    "--filter",
    `label=com.docker.compose.project=${COMPOSE_PROJECT}`,
  ]);
  if (volumes.includes(STATE_VOLUME))
    throw new Error(
      "a verify stack is already up on this daemon: `report` reads it, `down` removes it",
    );
  if (product.length > 0 || compose !== "")
    throw new Error(
      "this Docker daemon runs a Mend server of its own (Compose project mend or its volumes): the stack uses the same names, so it refuses. Run it in a Mend session, or point DOCKER_HOST at an empty daemon.",
    );
}

/** The refusal a start meets when another start holds the daemon. */
const CLAIM_REFUSED =
  "a verify stack is already starting or up on this daemon: `report` reads it, `down` removes it";

/**
 * Claim the daemon for this start before anything is built (lifecycle.mjs): of two starts at once,
 * one holds the claim and the other is refused, so they never share names or state.
 */
async function claimDaemon(claimId) {
  if (!(await claim(dockerOut, { claimId, image: FIXTURE_BASE_IMAGE })))
    throw new Error(CLAIM_REFUSED);
}

/**
 * Build, install and check a stack. `claimId` names this start's claim, and `claimWith` makes it:
 * `serve` passes its watchdog's (the watchdog creates the claim, so a create in flight belongs to
 * the process that outlives `serve`). Everything that can fail after the claim runs inside the
 * cleanup below, which removes this start's generation and nobody else's (`--keep` leaves it).
 */
async function up(args, { claimId = randomUUID(), claimWith = claimDaemon } = {}) {
  const { flags, sources: specs } = parseFlags(args);
  if (insideCaptureRoot(cacheDir))
    throw new Error(
      `${cacheDir} is inside a capture root: the stack's files would be saved with the session. Set MEND_VERIFY_STACK_CACHE outside /workspace.`,
    );
  await mkdir(cacheDir, { recursive: true, mode: 0o700 });
  await mkdir(dockerEnv.DOCKER_CONFIG, { recursive: true, mode: 0o700 });
  await mkdir(dockerEnv.HOME, { recursive: true, mode: 0o700 });
  const started = Date.now();
  const phases = {};
  const runId = new Date().toISOString().replace(/[:.]/g, "-");
  const logs = join(cacheDir, "logs", runId);

  await docker(["version", "--format", "{{.Server.Version}}"]).catch(() => {
    throw new Error(
      "no Docker daemon answers: in a session, turn on the project's Docker service (Settings · workspace image)",
    );
  });
  await assertDaemonIsFree();
  // The base of the fixture's sessions, and the image the claim and the socket probe run.
  await docker(["pull", "--quiet", FIXTURE_BASE_IMAGE], { timeout: 15 * 60_000 });
  // Before the claim, so a trim that trips cannot strand one.
  await trimCaches();
  await mkdir(logs, { recursive: true });
  await claimWith(claimId);
  try {
    return await upClaimed(flags, specs, { started, phases, logs });
  } catch (error) {
    if (flags.keep) throw error;
    say("verify stack · up failed; removing what it made (--keep keeps it for a look)");
    // From shared to exclusive on the same lock: no other start or teardown acts meanwhile.
    const removed = await exec("flock", ["-x", "-w", "600", String(LOCK_FD)], { env: process.env })
      .then(() => takeDown(claimId))
      .catch((cleanup) => `failed: ${cleanup.message}`);
    if (removed !== "removed") say(`verify stack · removing it: ${removed}`);
    throw error;
  }
}

async function upClaimed(flags, specs, { started, phases, logs }) {
  const repos = await sessionRepos();
  const parsed = Object.fromEntries(
    Object.keys(REPOSITORIES).map((repository) => [
      repository,
      parseSource(
        repository,
        specs[repository] ?? defaultSpec(repository, { mendRoot, sessionRepos: repos }),
      ),
    ]),
  );
  say("verify stack · resolving sources");
  const resolved = await timed(phases, "sources", async () =>
    Object.fromEntries(
      await Promise.all(
        Object.entries(parsed).map(async ([name, source]) => [name, await resolveSource(source)]),
      ),
    ),
  );
  for (const source of Object.values(resolved)) say(`  ${describeSource(source)}`);

  const contexts = await timed(phases, "contexts", async () =>
    Object.fromEntries(
      await Promise.all(
        Object.entries(resolved)
          .filter(([, source]) => source.kind !== "pinned")
          .map(async ([name, source]) => [name, await contextOf(source)]),
      ),
    ),
  );
  const cliVersion = JSON.parse(await showFile(resolved.mend, "apps/cli/package.json")).version;
  // Setup runs offline, so every image it starts is pulled first: the bundle's Compose file, and
  // the package and image mirrors' overlay, which setup adds by default where the source has it.
  const composeYaml = [
    await showFile(resolved.mend, "deploy/docker/compose.v2.yaml"),
    await showFile(resolved.mend, "deploy/docker/compose.mirrors.yaml").catch(() => ""),
  ].join("\n");
  const relay = relayEndpoint(process.env.DOCKER_HOST, flags.port);
  const { socket, rootless } = await daemonSocket();

  // Every build starts at once. The bundle copies Core's three images in, so it waits for them;
  // it only names the sealantd image (the bundled worker bakes it into workspace images when an
  // inner session first launches), so sealantd's cargo build runs on beside the bundle and the
  // install, and the stack is ready once it is done too.
  say("verify stack · building images (logs: " + logs + ")");
  await ensureBuildx();
  const outcomes = {};
  const upstream = imageNames(resolved, { cliVersion, upstreamIds: [] });
  const component = async (name, work) => {
    const outcome = await timed(phases, `build:${name}`, work);
    outcomes[name] = outcome;
    say(`  ${name} · ${outcome} · ${formatSeconds(phases[`build:${name}`])}`);
  };
  const sealantdBuild =
    upstream.sealantd === null
      ? Promise.resolve()
      : component("sealantd", () =>
          build(logs, "sealantd", {
            context: contexts.sealantd,
            dockerfile: "docker/Dockerfile",
            tag: upstream.sealantd,
            labels: { [`${STACK_LABEL}.source`]: `sealantd@${resolved.sealantd.commit}` },
          }),
        );

  const coreBuilds =
    upstream.sealantApi === null
      ? []
      : [
          ["api", upstream.sealantApi],
          ["worker", upstream.sealantWorker],
          ["ssh-gateway", upstream.sealantSshGateway],
        ].map(([app, tag]) =>
          component(`sealant-${app}`, () =>
            build(logs, `sealant-${app}`, {
              context: contexts.sealant,
              dockerfile: `apps/${app}/Dockerfile`,
              tag,
              labels: { [`${STACK_LABEL}.source`]: `sealant@${resolved.sealant.commit}` },
            }),
          ),
        );
  const cliBuild = component("mend-cli", () =>
    build(logs, "mend-cli", {
      context: contexts.mend,
      dockerfile: { text: CLI_DOCKERFILE },
      tag: upstream.cli,
    }),
  );
  // Both are awaited below; a failure before then is not an unhandled rejection.
  for (const pending of [sealantdBuild, cliBuild]) pending.catch(() => undefined);
  const pulls = timed(phases, "pulls", () =>
    Promise.all(
      composeImages(composeYaml).map((image) =>
        docker(["pull", "--quiet", image], { timeout: 15 * 60_000 }),
      ),
    ),
  );
  await Promise.all([...coreBuilds, pulls]);
  // sealantd by its tree (its tag), Core by the image ids the bundle copies.
  const upstreamIds = [
    resolved.sealantd.kind === "pinned" ? "pinned" : resolved.sealantd.tree,
    ...(await Promise.all(
      [upstream.sealantApi, upstream.sealantWorker, upstream.sealantSshGateway].map((tag) =>
        tag === null ? "pinned" : imageId(tag),
      ),
    )),
  ];
  const images = imageNames(resolved, { cliVersion, upstreamIds });
  const bundleBuild = component("mend", () =>
    build(logs, "mend", {
      context: contexts.mend,
      dockerfile: "Dockerfile",
      tag: images.mend,
      args: mendBuildArgs(images),
      labels: { [`${STACK_LABEL}.source`]: `mend@${resolved.mend.commit}` },
    }),
  );
  await Promise.all([cliBuild, bundleBuild]);

  // Setup: the product's own install, run where its files are the daemon's files.
  const origins = innerOrigins(relay);
  const state = {
    version: 1,
    daemon: await daemonKey(),
    // `building` until every image is built and the stack is installed and set up; then `ready`.
    // The web can answer while sealantd still builds: only `ready` means the stack is whole.
    phase: "building",
    createdAt: new Date(started).toISOString(),
    sources: Object.fromEntries(
      Object.entries(resolved).map(([name, source]) => [
        name,
        source.kind === "pinned"
          ? { kind: "pinned" }
          : {
              kind: source.kind,
              ...(source.kind === "pr" ? { number: source.number } : {}),
              ...(source.kind === "ref" ? { ref: source.ref } : {}),
              ...(source.kind === "worktree" ? { path: source.path, dirty: source.dirty } : {}),
              commit: source.commit,
              tree: source.tree,
              description: describeSource(source),
            },
      ]),
    ),
    images,
    builds: outcomes,
    relay,
    url: origins.url,
    dockerSocket: socket,
    rootless,
    phases,
    logs,
  };
  await writeState(state);
  // From here on the stack creates on the daemon: what has its shape is recorded in the ledger.
  return recording(
    () =>
      install(flags, state, {
        logs,
        started,
        phases,
        contexts,
        images,
        origins,
        socket,
        sealantdBuild,
      }),
    { state, shape: SHAPES.install },
  );
}

/** Set up the inner server, its relay, account and fixture, then check it: a recording window. */
async function install(
  flags,
  state,
  { logs, started, phases, contexts, images, origins, socket, sealantdBuild },
) {
  say(`verify stack · mend server setup ${images.version}`);
  await docker(["volume", "create", "--label", `${STACK_LABEL}=1`, STATE_VOLUME]);
  await timed(phases, "setup", async () => {
    const setup = cliRun(
      state,
      [
        "server",
        "setup",
        "--docker-socket",
        socket,
        "--version",
        images.version,
        "--assets-dir",
        ASSETS_DIR,
        "--offline",
        // The server's own port, on the daemon's loopback: setup's check and the relay go through
        // the relay's port, and a rootless daemon cannot publish one port on loopback and on
        // every interface at once.
        "--port",
        String(flags.port + SERVER_PORT_OFFSET),
        "--ssh-port",
        "2222",
        "--url",
        origins.url,
        ...origins.extra.flatMap((origin) => ["--origin", origin]),
      ],
      { home: "server", log: join(logs, "setup.log") },
    );
    // Setup waits for health at --url, which the relay serves: the relay joins the Compose
    // network as soon as setup has made it.
    const relayed = (async () => {
      for (let i = 0; i < 600; i++) {
        const network = await docker(["network", "inspect", COMPOSE_NETWORK]).then(
          () => true,
          () => false,
        );
        if (network) return startRelay(state);
        await pause(500);
      }
      throw new CommandError(`setup never made the ${COMPOSE_NETWORK} network`);
    })();
    await Promise.all([setup, relayed]);
  });
  say(`  setup · ${formatSeconds(phases.setup)}`);

  await timed(phases, "account", () => firstAccount(state));
  await timed(phases, "fixture", () => fixtureProject(state, contexts.mend));
  // Inner sessions need it: their workspace images are built from it.
  await sealantdBuild;
  phases.ready = Math.round(since(started) * 10) / 10;
  state.phase = "ready";
  state.readyAt = new Date().toISOString();
  await writeState(state);
  say(`verify stack · ready in ${formatSeconds(phases.ready)} · ${origins.url}`);
  if (flags.check) await check(state);
  await writeState(state);
  return state;
}

async function startRelay(state) {
  // A TCP relay on the Compose network: the browser origin's port, published where the session
  // reaches this daemon, to the inner web. Each connection is piped; nothing is read or kept.
  const code = [
    'const net = require("node:net");',
    "net.createServer((c) => {",
    `  const u = net.connect(${INNER_WEB_PORT}, "mend");`,
    "  c.pipe(u); u.pipe(c);",
    '  c.on("error", () => u.destroy()); u.on("error", () => c.destroy());',
    `}).listen(${INNER_WEB_PORT}, "0.0.0.0");`,
  ].join("\n");
  await docker([
    "run",
    "--detach",
    "--name",
    RELAY_CONTAINER,
    "--label",
    `${STACK_LABEL}=1`,
    "--restart",
    "unless-stopped",
    "--network",
    COMPOSE_NETWORK,
    "--publish",
    state.relay.publish,
    "--entrypoint",
    "node",
    state.images.cli,
    "-e",
    code,
  ]);
}

const relayOrigin = (state) => `http://${state.relay.host}:${state.relay.port}`;

/** The inner server's first account: generated password, kept in the state volume only. */
async function firstAccount(state) {
  const password = randomBytes(32).toString("hex");
  const response = await fetch(`${relayOrigin(state)}/api/auth/sign-up/email`, {
    method: "POST",
    headers: { origin: state.url, "content-type": "application/json" },
    body: JSON.stringify({ email: INNER_ACCOUNT_EMAIL, password, name: "Verifier" }),
    signal: AbortSignal.timeout(60_000),
  });
  await response.body?.cancel();
  const token = response.headers.get("set-auth-token");
  if (!response.ok || !token)
    throw new CommandError(`the inner server refused the first account (HTTP ${response.status})`);
  // The CLI's own configuration, as `mend login` writes it; the inner CLI reads it.
  await writePrivate(
    state,
    "client/.config/mend/cli.json",
    JSON.stringify({ url: state.url, token, deviceId: randomUUID() }),
  );
  await writePrivate(
    state,
    "client/.config/mend-verify-stack/account.json",
    JSON.stringify({ email: INNER_ACCOUNT_EMAIL, password }),
  );
}

async function innerToken(state) {
  return JSON.parse(await readPrivate(state, "client/.config/mend/cli.json")).token;
}

async function innerApi(state, route, { method = "GET", body } = {}) {
  const token = await innerToken(state);
  const response = await fetch(`${relayOrigin(state)}/api${route}`, {
    method,
    headers: {
      authorization: `Bearer ${token}`,
      ...(body === undefined ? {} : { "content-type": "application/json" }),
    },
    ...(body === undefined ? {} : { body: JSON.stringify(body) }),
    signal: AbortSignal.timeout(60_000),
  });
  if (!response.ok) {
    await response.body?.cancel();
    throw new CommandError(`inner API ${method} ${route.split("?")[0]}: HTTP ${response.status}`);
  }
  return response.json();
}

/**
 * A one-commit repository served over git's HTTP protocol on the Compose network (the packaged
 * acceptance's fixture), adopted as `verify-fixture`, whose sessions run on a plain Node base with
 * no Docker service: what `mend run -- true` needs and nothing more. Another project is
 * `stack.mjs mend adopt <url>` away.
 */
async function fixtureProject(state, mendContext) {
  await docker(["volume", "create", "--label", `${STACK_LABEL}=1`, FIXTURE_VOLUME]);
  const init = [
    "set -e",
    "if [ ! -d /fixture/repo.git ]; then",
    "  git init -q -b main /tmp/src",
    '  printf "# Verify fixture\\n" > /tmp/src/README.md',
    "  git -C /tmp/src add README.md",
    "  git -C /tmp/src -c user.name=Mend -c user.email=verify@verify-stack.invalid commit -qm base",
    "  git clone -q --bare /tmp/src /fixture/repo.git",
    "  git -C /fixture/repo.git update-server-info",
    "fi",
    "exec node /fixture/packaged-git-fixture.mjs",
  ].join("\n");
  await docker([
    "create",
    "--name",
    FIXTURE_CONTAINER,
    "--label",
    `${STACK_LABEL}=1`,
    "--restart",
    "unless-stopped",
    "--network",
    COMPOSE_NETWORK,
    "--volume",
    `${FIXTURE_VOLUME}:/fixture`,
    "--entrypoint",
    "sh",
    state.images.mend,
    "-c",
    init,
  ]);
  for (const file of ["packaged-git-fixture.mjs", "packaged-server-assertions.mjs"])
    await docker([
      "cp",
      join(mendContext, "scripts", file),
      `${FIXTURE_CONTAINER}:/fixture/${file}`,
    ]);
  await docker(["start", FIXTURE_CONTAINER]);
  const url = `http://${FIXTURE_CONTAINER}:9080/repo.git`;
  for (let i = 0; ; i++) {
    const served = await docker(["exec", FIXTURE_CONTAINER, "git", "ls-remote", url]).then(
      () => true,
      () => false,
    );
    if (served) break;
    if (i > 60) throw new CommandError("the fixture repository never answered");
    await pause(500);
  }
  // Shared, so a person invited to the inner server (`mend invite`) sees it too.
  await cliRun(state, ["adopt", url, "--name", FIXTURE_PROJECT, "--shared"], {
    timeout: 5 * 60_000,
  });
  const projects = await innerApi(state, "/projects");
  const project = projects.find((item) => item.name === FIXTURE_PROJECT);
  if (!project) throw new CommandError("the fixture project is not listed after adoption");
  await innerApi(state, `/projects/${project.id}/workspace-image`, {
    method: "PUT",
    body: {
      workspaceImage: {
        mode: "custom",
        baseImage: FIXTURE_BASE_IMAGE,
        packages: [],
        setupCommands: [],
        services: { docker: false },
      },
    },
  });
}

/** `mend run -- true` on the inner Sealant: the stack launches a session end to end. */
async function check(state) {
  say("verify stack · check · inner mend run -- true");
  const started = Date.now();
  const name = `check-${Date.now().toString(36)}`;
  await cliRun(state, ["run", "--project", FIXTURE_PROJECT, "--name", name, "--", "true"], {
    timeout: 15 * 60_000,
    log: join(state.logs, `${name}.log`),
  });
  const projects = await innerApi(state, "/projects");
  const project = projects.find((item) => item.name === FIXTURE_PROJECT);
  const detail = await innerApi(state, `/projects/${project.id}?deadEnds=include`);
  const session = detail.sessions?.find((item) => item.branch === `mend/${name}`);
  // `mend run` returns once the command exits; the session settles after its Stop saves.
  let status = null;
  if (session !== undefined) {
    const settleBy = Date.now() + 180_000;
    while (Date.now() < settleBy) {
      status = (await innerApi(state, `/sessions/${session.id}`)).session.status;
      if (status === "completed" || status === "failed" || status === "stopped") break;
      await pause(1000);
    }
  }
  state.check = {
    command: "mend run -- true",
    session: session?.id ?? null,
    status,
    seconds: Math.round(since(started) * 10) / 10,
    at: new Date().toISOString(),
  };
  say(
    `  inner session ${session?.id.slice(0, 8) ?? "?"} · ${status ?? "not found"} · ${formatSeconds(state.check.seconds)}`,
  );
  if (status !== "completed")
    throw new CommandError(`the inner session ended ${status ?? "unseen"}, not completed`);
}

// ─── report ─────────────────────────────────────────────────────────────────

/** What every process of this daemon holds: PSS summed from a probe in its process namespace. */
async function measureMemory(state) {
  if (state.rootless) {
    // A rootless daemon's process namespace is the session sidecar's: every process there is the
    // stack's (dockerd, containerd, the inner server, its sessions). Privileged inside the user
    // namespace only, so the probe reads every process's smaps.
    const text = await dockerOut(
      [
        "run",
        "--rm",
        ...transient("memory"),
        "--privileged",
        "--pid",
        "host",
        "--network",
        "none",
        "--entrypoint",
        "sh",
        state.images.mend,
        "-c",
        MEMORY_PROBE,
      ],
      { timeout: 120_000 },
    );
    const memory = parseMemory(text);
    return { method: "pss of every process of the session's Docker daemon", ...memory };
  }
  // Any other daemon is shared with the machine: the stack's containers only, as Docker counts.
  const ids = await stackContainers();
  if (ids.length === 0) return { method: "docker stats", totalKb: 0, processes: [] };
  const lines = await dockerOut([
    "stats",
    "--no-stream",
    "--format",
    "{{.Name}} {{.MemUsage}}",
    ...ids,
  ]);
  const unit = { B: 1 / 1024, KiB: 1, MiB: 1024, GiB: 1024 * 1024 };
  const processes = lines.split("\n").map((line) => {
    const [name, usage] = line.split(" ");
    const match = /^([\d.]+)(B|KiB|MiB|GiB)$/.exec(usage ?? "");
    return { command: name, kb: match ? Math.round(Number(match[1]) * unit[match[2]]) : 0 };
  });
  return {
    method: "docker stats of the stack's containers",
    totalKb: processes.reduce((sum, item) => sum + item.kb, 0),
    processes,
  };
}

const nonEmptyLines = (output) => output.split("\n").filter(Boolean);

async function inspectAll(ids) {
  if (ids.length === 0) return [];
  return JSON.parse(await dockerOut(["inspect", ...ids]));
}

/**
 * What is on the daemon, `docker inspect`ed: every container, volume and network. A teardown plans
 * from it (lib.mjs `planTeardown`).
 */
async function inventory() {
  const containers = await inspectAll(
    nonEmptyLines(await dockerOut(["ps", "--all", "--quiet", "--no-trunc"])),
  );
  const names = nonEmptyLines(await dockerOut(["volume", "ls", "--quiet"]));
  const volumes =
    names.length === 0 ? [] : JSON.parse(await dockerOut(["volume", "inspect", ...names]));
  const ids = nonEmptyLines(await dockerOut(["network", "ls", "--quiet", "--no-trunc"]));
  const networks =
    ids.length === 0 ? [] : JSON.parse(await dockerOut(["network", "inspect", ...ids]));
  return { containers, volumes, networks };
}

/** The stack's containers on the daemon now: what the ledger recorded, and its own. */
async function stackContainers() {
  const now = await inventory();
  return planTeardown({ ledger: await readLedger(now.volumes), ...now }).containers.map(
    (item) => item.Id,
  );
}

// ─── the ledger ─────────────────────────────────────────────────────────────

/**
 * Where this daemon's ledger lives: what the stack made on it, by exact identity, one file per
 * recording window, under `<cache>/ledger/<daemon>/` (the daemon as the lock names it), so a
 * teardown of one daemon never reads or removes another's. Each directory is checked as the lock's
 * is (`privateDirectory`). A teardown removes only entries that also have the stack's shape
 * (lib.mjs `planTeardown`).
 */
async function ledgerDirectory() {
  privateDirectory(join(cacheDir, "ledger"));
  return privateDirectory(join(cacheDir, "ledger", await daemonKey()));
}

/**
 * The daemon's containers (id, name, Compose project) and networks (id, name), and its volumes by
 * name and creation time. Retried when something goes between its listing and its inspection.
 */
async function snapshot() {
  const rows = (output) => nonEmptyLines(output).map((line) => line.split("\t"));
  for (let attempt = 0; ; attempt++) {
    try {
      const names = nonEmptyLines(await dockerOut(["volume", "ls", "--quiet"]));
      const volumes =
        names.length === 0
          ? []
          : rows(
              await dockerOut([
                "volume",
                "inspect",
                "--format",
                "{{.Name}}\t{{.CreatedAt}}",
                ...names,
              ]),
            ).map(([name, createdAt]) => ({ name, createdAt }));
      const containers = rows(
        await dockerOut([
          "ps",
          "--all",
          "--no-trunc",
          "--format",
          '{{.ID}}\t{{.Names}}\t{{.Label "com.docker.compose.project"}}',
        ]),
      ).map(([id, name, compose = ""]) => ({ id, name, compose }));
      const networks = rows(
        await dockerOut(["network", "ls", "--no-trunc", "--format", "{{.ID}}\t{{.Name}}"]),
      ).map(([id, name]) => ({ id, name }));
      return { containers, networks, volumes };
    } catch (error) {
      if (attempt >= 4) throw error;
      await pause(500);
    }
  }
}

async function writeAtomically(file, value) {
  await writeFile(`${file}.tmp`, `${JSON.stringify(value)}\n`, { mode: 0o600 });
  await rename(`${file}.tmp`, file);
}

/**
 * Run `work` as a recording window: what appears on the daemon while it runs and has the window's
 * `shape` (lib.mjs `SHAPES`: `install` for `up`, `session` for `mend` and `check`) is the stack's.
 * The session's daemon is shared with its agent and its person, so anything else that appears
 * meanwhile (a dev database, say) is not recorded. The window's file is written when it opens,
 * every two seconds while it runs and once more when it ends, so a window cut short by a kill has
 * recorded all but its last seconds and says so (`closed: false`). When `state` is given, the whole
 * ledger is also copied into the state volume, for a `down` run without this cache directory.
 */
async function recording(work, { state = null, shape = SHAPES.session } = {}) {
  const dir = await ledgerDirectory();
  const window = { window: randomUUID(), startedAt: new Date().toISOString() };
  const file = join(dir, `${window.window}.json`);
  const before = await snapshot();
  let made = madeSince(before, before, shape);
  const save = (closed) => writeAtomically(file, { ...window, closed, ...made });
  await save(false);
  const ticker = { open: true, wake: () => undefined };
  const ticks = (async () => {
    for (;;) {
      await new Promise((done) => {
        ticker.wake = done;
        setTimeout(done, 2000);
      });
      if (!ticker.open) return;
      try {
        made = madeSince(before, await snapshot(), shape);
        await save(false);
      } catch {
        // The next tick, or the close, records it.
      }
    }
  })();
  try {
    return await work();
  } finally {
    ticker.open = false;
    ticker.wake();
    await ticks;
    try {
      made = madeSince(before, await snapshot(), shape);
      await save(true);
    } catch (error) {
      say(
        `verify stack · the ledger's last record failed (${error.message}): it keeps what the recording saw until then, marked as cut short`,
      );
    }
    if (state !== null) {
      const ledger = mergeLedgers((await readLedgerFiles()).windows);
      await writePrivate(state, "ledger.json", JSON.stringify(ledger)).catch(() => undefined);
    }
  }
}

/** A ledger file: this user's own regular file, private to them, read without following a link. */
function readPrivateFile(path) {
  const fd = openSync(path, constants.O_RDONLY | constants.O_NOFOLLOW);
  try {
    const file = fstatSync(fd);
    if (!file.isFile() || file.uid !== process.getuid() || (file.mode & 0o077) !== 0)
      throw new Error(`${path} must be this user's own file, private to them (0600)`);
    return readFileSync(fd, "utf8");
  } finally {
    closeSync(fd);
  }
}

/** A ledger's JSON, or a refusal that names where it came from: a teardown removes nothing then. */
function parseLedger(text, where) {
  try {
    const ledger = JSON.parse(text);
    if (ledger === null || typeof ledger !== "object") throw new Error("not an object");
    return ledger;
  } catch (error) {
    throw new CommandError(
      `the ledger in ${where} cannot be read (${error.message}); nothing was removed. Move it aside to tear down the stack's own infrastructure only.`,
    );
  }
}

/** Every window's file of this daemon's ledger, and the windows that were cut short. */
async function readLedgerFiles() {
  const dir = await ledgerDirectory();
  const windows = (await readdir(dir))
    .filter((name) => name.endsWith(".json"))
    .map((name) => parseLedger(readPrivateFile(join(dir, name)), join(dir, name)));
  return { windows, cutShort: windows.filter((window) => !window.closed) };
}

/**
 * The stack's ledger for this daemon: this cache directory's windows and the copy `up` left in the
 * stack's state volume, merged (the copy read with `--pull never`: a teardown fetches nothing).
 */
async function readLedger(volumes) {
  const { windows, cutShort } = await readLedgerFiles();
  const stateVolume = volumes.find(
    (volume) => volume.Name === STATE_VOLUME && volume.Labels?.[STACK_LABEL] === "1",
  );
  if (stateVolume === undefined) return { ...mergeLedgers(windows), cutShort };
  const copy = await dockerOut([
    "run",
    "--rm",
    "--pull",
    "never",
    ...transient("ledger"),
    "--network",
    "none",
    "--volume",
    `${STATE_VOLUME}:/state:ro`,
    "--entrypoint",
    "sh",
    FIXTURE_BASE_IMAGE,
    "-c",
    "if [ -f /state/ledger.json ]; then cat /state/ledger.json; fi",
  ]).catch(() => "");
  const copies = copy ? [parseLedger(copy, `the state volume's ledger.json`)] : [];
  return { ...mergeLedgers([...windows, ...copies]), cutShort };
}

async function report(args) {
  const { flags } = parseFlags(args);
  const state = await readState();
  if (!state) throw new Error("no verify stack here: `up` starts one");
  const memory = await measureMemory(state);
  const isolation = isolationFindings(await inspectAll(await stackContainers()), outerSecrets);
  // Read-only: what it measures is printed with the stack's state, never written back.
  const measured = {
    memory: {
      at: new Date().toISOString(),
      method: memory.method,
      totalKb: memory.totalKb,
      top: memory.processes.slice(0, 12),
    },
    isolation: { checked: outerSecrets.length, findings: isolation },
  };
  if (flags.json) return say(JSON.stringify({ ...state, ...measured }, null, 2));
  say(`verify stack · ${state.phase ?? "ready"}`);
  for (const source of Object.values(state.sources))
    say(`  ${source.description ?? "pinned (the release Mend pins)"}`);
  say(`  web · ${state.url} (from the session: ${relayOrigin(state)})`);
  for (const [phase, seconds] of Object.entries(state.phases))
    say(`  ${phase.padEnd(22)} ${formatSeconds(seconds)}`);
  if (state.check)
    say(
      `  check: ${state.check.command} · ${state.check.status} · ${formatSeconds(state.check.seconds)}`,
    );
  say(`  memory · ${formatKb(memory.totalKb)} · ${memory.method}`);
  for (const item of memory.processes.slice(0, 8))
    say(`    ${formatKb(item.kb).padStart(9)}  ${item.command}`);
  // What was looked at, and only that: each container's environment, command and labels.
  say(
    outerSecrets.length === 0
      ? "  isolation · not checked: no credential of the session is readable here"
      : isolation.length === 0
        ? `  isolation · the session's credential (${outerSecrets.length} value(s)) is in no container's environment, command or labels`
        : `  isolation · FOUND in ${isolation.join(", ")}`,
  );
  if (isolation.length > 0) process.exitCode = 1;
}

// ─── down ───────────────────────────────────────────────────────────────────

async function down(args) {
  const { flags } = parseFlags(args);
  const owner = await currentClaim(dockerOut);
  const volumes = (await dockerOut(["volume", "ls", "--quiet"])).split("\n").filter(Boolean);
  let removed = null;
  if (owner.state === "present") {
    await takeDown(owner.claim ?? "", (counts) => (removed = counts));
  } else if (volumes.includes(STATE_VOLUME) || flags.force) {
    // Remains with no generation (a start killed before it claimed): this process holds the
    // daemon's lock exclusively, so no start is building beside the sweep.
    removed = await removeResources(null);
  } else if (!flags.purge) {
    throw new Error("no verify stack on this daemon (--force sweeps what one left anyway)");
  }
  if (flags.purge) await purgeCaches();
  say(
    `verify stack · removed ${removed?.containers ?? 0} container(s), ${removed?.volumes ?? 0} volume(s)${flags.purge ? "; images, build cache and every cache directory purged" : "; images kept for the next up"}`,
  );
}

/**
 * Take generation `claimId` down (lifecycle.mjs `teardownGeneration`), under the daemon's lock held
 * exclusively: `"removed"`, `"gone"` or `"not-ours"`. `onRemoved` hears the counts.
 */
const takeDown = (claimId, onRemoved = () => {}) =>
  teardownGeneration({
    docker: dockerOut,
    claimId,
    removeResources: async (ownerId) => onRemoved(await removeResources(ownerId)),
  });

/**
 * What the stack's ledger recorded and its own infrastructure (lib.mjs `planTeardown`), then
 * `ownerId` last. It runs only under the daemon's lock held exclusively, so no start of the stack
 * records or builds meanwhile. Nothing else is removed: what looks like the stack's but is not in
 * the ledger is reported with the commands that remove it by hand. When a removal fails, the state
 * volume and the ledger stay, so the next teardown tries again; the state file goes before the
 * owner, so no later generation's state is ever this one's to remove.
 */
async function removeResources(ownerId) {
  const now = await inventory();
  const ledger = await readLedger(now.volumes);
  const plan = planTeardown({ ledger, ...now });
  const failures = [];
  const remove = (args, what) =>
    docker(args).then(
      () => say(`verify stack · removed ${what}`),
      (error) => failures.push(`${what} (${error.message})`),
    );
  for (const item of plan.containers)
    await remove(
      ["rm", "--force", "--volumes", item.Id],
      `container ${item.Name.replace(/^\//, "")} (${item.Id.slice(0, 12)})`,
    );
  for (const volume of plan.volumes.filter((item) => item.Name !== STATE_VOLUME))
    await remove(["volume", "rm", "--force", volume.Name], `volume ${volume.Name}`);
  // A network holds no data: one still in use by something unrecorded is reported, not retried.
  for (const network of plan.networks)
    await docker(["network", "rm", network.Id]).then(
      () => say(`verify stack · removed network ${network.Name}`),
      () =>
        say(
          `verify stack · left network ${network.Name}: something the stack did not make uses it`,
        ),
    );
  for (const window of ledger.cutShort)
    say(
      `verify stack · a recording that began ${window.startedAt} was cut short: what it made in its last seconds is not recorded`,
    );
  const why = {
    "made again": "made again after the stack recorded it",
    "not the stack's shape":
      "made while a recording was open, but shaped like nothing the stack makes",
    "not recorded": "shaped like the stack's, but never recorded as made by it",
  };
  for (const [reason, says] of Object.entries(why)) {
    const items = plan.leftAlone.filter((item) => item.reason === reason);
    if (items.length > 0)
      say(
        `verify stack · left alone (${says}): ${items.map((item) => `${item.kind} ${item.name}`).join(", ")}`,
      );
  }
  if (plan.leftAlone.length > 0) {
    say("  to remove them by hand, if they are the stack's:");
    for (const line of manualRemoval(plan.leftAlone)) say(`    ${line}`);
  }
  if (failures.length > 0)
    throw new CommandError(
      `could not remove ${failures.join("; ")}; the ledger is kept, so the next down tries again`,
    );
  if (plan.volumes.some((item) => item.Name === STATE_VOLUME))
    await remove(["volume", "rm", "--force", STATE_VOLUME], `volume ${STATE_VOLUME}`);
  await rm(await ledgerDirectory(), { recursive: true, force: true });
  // The state file names one daemon's stack: another daemon's teardown leaves it.
  const state = await readState();
  if (state !== null && (state.daemon === undefined || state.daemon === (await daemonKey())))
    await rm(stateFile, { force: true });
  if (ownerId !== null) await docker(["rm", "--force", ownerId]);
  return {
    containers: plan.containers.length + (ownerId === null ? 0 : 1),
    volumes: plan.volumes.length,
  };
}

/**
 * Everything the stack keeps for its next start: its images, BuildKit's cache on this daemon (layers
 * and cache mounts, cargo's included), and its cache directories (contexts, packed packages, the
 * bare repositories, logs). Works with or without a stack up.
 */
async function purgeCaches() {
  const images = (await dockerOut(["image", "ls", "--quiet", "--filter", `label=${STACK_LABEL}=1`]))
    .split("\n")
    .filter(Boolean);
  if (images.length > 0)
    await docker(["image", "rm", "--force", ...new Set(images)]).catch(() => undefined);
  await ensureBuildx();
  await docker(["buildx", "prune", "--all", "--force"]);
  for (const dir of ["contexts", "packages", "git", "logs"])
    await rm(join(cacheDir, dir), { recursive: true, force: true });
}

/** How many entries each cache directory keeps across starts; older ones go at the next `up`. */
const RETENTION = { contexts: 6, packages: 6, logs: 10 };

async function trimCaches() {
  for (const [dir, keep] of Object.entries(RETENTION)) {
    const root = join(cacheDir, dir);
    const entries = [];
    for (const name of await readdir(root).catch(() => [])) {
      // An entry that vanished or cannot be read is skipped, not fatal: trimming is housekeeping.
      const info = await lstat(join(root, name)).catch(() => null);
      if (info !== null) entries.push({ name, mtimeMs: info.mtimeMs });
    }
    for (const name of beyondRetention(entries, keep))
      await rm(join(root, name), { recursive: true, force: true }).catch((error) =>
        say(`verify stack · could not trim ${dir}/${name}: ${error.message}`),
      );
  }
}

// ─── serve ──────────────────────────────────────────────────────────────────

/**
 * `up`, then hold while the Service runs. The Service's port is the relay's: Mend dials the
 * workspace loopback, then the Docker sidecar.
 *
 * The stack goes when this process goes, however it goes. Mend stops a Service by hanging up its
 * terminal (SIGHUP to the process group, SIGKILL two seconds later, sealantd `sealant-pty` close),
 * a verifier may be killed outright, and `up` may fail. So the teardown does not run here but in a
 * watchdog, a process in a session of its own, out of the group's reach (lifecycle.mjs `watch`).
 * The watchdog also makes the claim, when this process asks: a create still in flight when this
 * process dies belongs to the watchdog, which waits for it however long it takes and then takes
 * down what it created. It takes down only its own generation. A start that ends holding no claim
 * stops its watchdog.
 */
async function serve(args) {
  const claimId = randomUUID();
  const watcher = startWatchdog(claimId);
  for (const signal of ["SIGHUP", "SIGTERM", "SIGINT"]) process.on(signal, () => process.exit(0));
  // The watchdog says when it listens, then answers the one claim request with the outcome.
  const replies = [];
  const waiting = [];
  // A channel that breaks is a watchdog that went away: `exited` says so; it never kills this one.
  watcher.on("error", () => undefined);
  watcher.on("message", (message) => {
    const waiter = waiting.shift();
    if (waiter) waiter(message);
    else replies.push(message);
  });
  const exited = new Promise((_, fail) =>
    watcher.once("exit", () => fail(new Error("the watchdog exited before it claimed"))),
  );
  exited.catch(() => undefined);
  const reply = () =>
    Promise.race([
      new Promise((done) => (replies.length > 0 ? done(replies.shift()) : waiting.push(done))),
      exited,
    ]);
  const claimWith = async () => {
    await reply(); // { ready: true }
    await new Promise((sent, fail) => {
      watcher.send({ claim: true }, (error) => {
        if (error) fail(error);
        else sent();
      });
    });
    const answer = await reply();
    // The channel has done its work: it no longer holds this process open.
    watcher.channel?.unref();
    if (answer?.claimed === true) return;
    throw new Error(answer?.claimed === false ? CLAIM_REFUSED : answer?.error);
  };
  let state;
  try {
    state = await up(args, { claimId, claimWith });
  } catch (error) {
    const owner = await currentClaim(dockerOut).catch(() => null);
    if (owner !== null && !(owner.state === "present" && owner.claim === claimId)) {
      try {
        process.kill(watcher.pid, "SIGTERM");
      } catch {
        // Already gone.
      }
    }
    throw error;
  }
  say(
    `verify stack · on your machine: mend service connect stack --port ${state.relay.port}, then open ${state.url}`,
  );
  say(
    "verify stack · sign in: node scripts/verify-stack/stack.mjs mend invite --role owner --days 1",
  );
  let last = null;
  for (;;) {
    const healthy = await fetch(`${relayOrigin(state)}/api/health`, {
      signal: AbortSignal.timeout(5000),
    }).then(
      (response) => response.ok,
      () => false,
    );
    if (healthy !== last) say(`verify stack · health ${healthy ? "answers" : "does not answer"}`);
    last = healthy;
    await pause(30_000);
  }
}

/**
 * A running process's start time (field 22 of /proc/<pid>/stat), so a reused pid is not mistaken
 * for it; null once it has ended, a zombie (state Z) included: nothing may have reaped it yet.
 */
const startTimeOf = (pid) => {
  try {
    const line = readFileSync(`/proc/${pid}/stat`, "utf8");
    const fields = line.slice(line.lastIndexOf(")") + 2).split(" ");
    if (fields[0] === "Z" || fields[0] === "X") return null;
    return fields[19] ?? null;
  } catch {
    return null;
  }
};

function startWatchdog(claimId) {
  const log = join(cacheDir, "logs", "watchdog.log");
  mkdirSync(dirname(log), { recursive: true });
  const out = openSync(log, "a");
  const started = startTimeOf(process.pid) ?? "";
  const child = spawn(
    process.execPath,
    [fileURLToPath(import.meta.url), "watchdog", String(process.pid), started, claimId],
    { detached: true, stdio: ["ignore", out, out, "ipc"], env: process.env },
  );
  child.unref();
  say(`verify stack · watchdog holds the stack to this process (log: ${log})`);
  return child;
}

/**
 * `watchdog <pid> <start time> <claim id>`: makes the claim when its supervisor asks (over IPC),
 * waits for the supervisor to end, then takes the generation down (lifecycle.mjs `watch`) through
 * `teardown`, a command that holds the daemon's lock exclusively.
 */
async function watchdog([pid, started, claimId]) {
  if (!claimId) throw new Error("watchdog needs the claim id it guards");
  const log = (line) => say(`${new Date().toISOString()} verify stack · ${pid} · ${line}`);
  // Nothing on the IPC channel ends this process: an error there is a supervisor gone.
  process.on("error", (error) => log(`ipc: ${error.code ?? error.message}`));
  let attempt = null;
  // Once the watchdog has settled whether this start holds a claim, it makes none: a request still
  // in the pipe from a supervisor that has died must not start a create nobody would watch.
  let settled = false;
  process.on("message", (message) => {
    if (message?.claim !== true || attempt !== null || settled) return;
    attempt = claim(dockerOut, { claimId, image: FIXTURE_BASE_IMAGE });
    void (async () => {
      try {
        const claimed = await attempt;
        log(claimed ? "claimed the daemon" : "refused: another start holds the daemon");
        sendSafely(process, { claimed }, log);
      } catch (error) {
        sendSafely(process, { error: error.message }, log);
      }
    })();
  });
  sendSafely(process, { ready: true }, log);
  // The channel never keeps this process alive; the supervisor's life does.
  process.channel?.unref();
  const outcome = await watch({
    alive: () => {
      const now = startTimeOf(pid);
      return now !== null && (started === "" || now === started);
    },
    claimed: () => {
      settled = true;
      return settleClaim({ attempt, docker: dockerOut, claimId, pause, log });
    },
    remove: () => runTeardown(claimId),
    pause,
    log,
  });
  log(
    {
      "taken-down": "the stack is down",
      gone: "no generation is up; nothing to take down",
      "not-ours": "the daemon's claim is another start's; nothing touched",
      "never-claimed": "this start never held a claim; nothing touched",
    }[outcome],
  );
}

/** What `teardown` exits with for each outcome; anything else is a failure to retry. */
const TEARDOWN_EXIT = { removed: 0, gone: 3, "not-ours": 4 };

/**
 * Run `teardown <claim id>` (which waits for the daemon's lock, exclusively) and answer its
 * outcome. Its output goes to this process's own (the watchdog's log).
 */
function runTeardown(claimId) {
  return new Promise((done, fail) => {
    const child = spawn(process.execPath, [fileURLToPath(import.meta.url), "teardown", claimId], {
      stdio: ["ignore", "inherit", "inherit"],
      env: process.env,
    });
    child.once("error", fail);
    child.once("close", (code) => {
      const outcome = Object.entries(TEARDOWN_EXIT).find(([, exit]) => exit === code)?.[0];
      if (outcome) done(outcome);
      else fail(new Error(`teardown exited ${code}`));
    });
  });
}

/** `teardown <claim id>`: take that generation down, holding the daemon's lock exclusively. */
async function teardown([claimId]) {
  const outcome = await takeDown(claimId ?? "", (removed) =>
    say(`verify stack · removed ${removed.containers} container(s), ${removed.volumes} volume(s)`),
  );
  process.exitCode = TEARDOWN_EXIT[outcome];
}

// ─── the daemon's lock ──────────────────────────────────────────────────────

/** This Docker daemon, as the lock and the ledger name it: a digest of `docker info`'s id. */
let daemonKeyOnce = null;
const daemonKey = () =>
  (daemonKeyOnce ??= dockerOut(["info", "--format", "{{.ID}}"]).then((id) =>
    digestOf(id).slice(0, 16),
  ));

/**
 * `dir`, made if it is missing, and checked: a directory of this user's, private to them (0700), and
 * no symlink. The lock and the ledger live in such directories, so nobody else can plant or hold
 * them. Returns `dir`.
 */
function privateDirectory(dir) {
  mkdirSync(dir, { recursive: true, mode: 0o700 });
  const where = lstatSync(dir);
  if (!where.isDirectory() || where.uid !== process.getuid() || (where.mode & 0o077) !== 0)
    throw new Error(
      `${dir} must be a directory of this user's, private to them (0700) and no symlink: the stack's lock and ledger live there`,
    );
  return dir;
}

/**
 * The lock file of this Docker daemon (`docker info` names it), private to the person: in a
 * directory of theirs, 0700, that is no symlink, opened 0600 without following one, and checked once
 * open to be their own regular file, so nobody else can create it first or hold it. Two people who
 * share one daemon therefore hold different locks: the daemon's claim still lets one stack up at a
 * time, but neither's teardown waits for the other's start (docs/operations/verify-stack.md).
 * Returns the open descriptor.
 */
async function openDaemonLock() {
  const dir = privateDirectory(join(cacheDir, "locks"));
  const path = join(dir, `${await daemonKey()}.lock`);
  const fd = openSync(path, constants.O_RDONLY | constants.O_CREAT | constants.O_NOFOLLOW, 0o600);
  const file = fstatSync(fd);
  if (!file.isFile() || file.uid !== process.getuid() || (file.mode & 0o077) !== 0) {
    closeSync(fd);
    throw new Error(`${path} must be this user's own file, private to them (0600)`);
  }
  return fd;
}

const BUSY =
  "this daemon's stack is busy: a serve, up, mend or check holds it (it may be building), or a teardown is under way. Stop serve to cancel it (mend service stop stack); its watchdog takes the stack down.";

/**
 * Take the daemon's lock, flock(2) through util-linux `flock` on a descriptor this process keeps
 * open: `shared` for a start (waits up to 10 minutes for a teardown to end), `exclusive` for `down`
 * (refused at once while a start or a teardown holds it), `exclusive-wait` for a watchdog's
 * teardown (waits for the start and every command it left running). The lock belongs to this
 * process's open file, which the kernel closes when the last process holding it ends, however it
 * ends, and so releases the lock.
 */
async function lockDaemon(mode) {
  const flock = await exec("flock", ["--version"], { env: process.env }).then(
    () => true,
    () => false,
  );
  if (!flock)
    throw new Error(
      "the verify stack needs flock(1) (util-linux) to hold its daemon's lock; it runs on Linux, as Mend sessions do",
    );
  lockFd = await openDaemonLock();
  const how = {
    shared: ["-s", "-w", "600"],
    exclusive: ["-x", "-n"],
    "exclusive-wait": ["-x"],
  }[mode];
  await exec("flock", [...how, String(LOCK_FD)], {
    env: process.env,
    timeout: 24 * 3600_000,
  }).catch(() => {
    closeSync(lockFd);
    lockFd = null;
    throw new Error(
      mode === "shared" ? "a teardown of this daemon's stack did not end within 10 minutes" : BUSY,
    );
  });
}

// ─── main ───────────────────────────────────────────────────────────────────

const HELP = `usage: node scripts/verify-stack/stack.mjs <command>

  up [sources] [--port <n>] [--no-check] [--keep]
                                           build and start the stack, then run the check
                                           (--keep: leave a failed start for a look)
  serve [sources] [--port <n>]             up, then hold; the stack goes when this stops
  mend <args…>                             the inner mend CLI, signed in as the first account
  check                                    inner mend run -- true, until its session settles
  report [--json]                          sources, timings, memory, isolation
  down [--purge] [--force]                 remove the stack (--purge: images, build cache, caches)

sources: --mend|--sealant|--sealantd <path|#pr|ref|pinned> (pinned: Core and sealantd only)
docs/operations/verify-stack.md has the rest.`;

async function main() {
  const [command, ...args] = process.argv.slice(2);
  switch (command) {
    case "up":
      await lockDaemon("shared");
      await up(args);
      return;
    case "serve":
      await lockDaemon("shared");
      await serve(args);
      return;
    case "teardown":
      await lockDaemon("exclusive-wait");
      await teardown(args);
      return;
    case "mend": {
      await lockDaemon("shared");
      const state = await readState();
      if (!state) throw new Error("no verify stack here: `up` starts one");
      // The inner CLI's own exit is this command's: its output went straight to the terminal. What
      // it makes on the daemon (an inner session's containers) goes into the ledger.
      await recording(() =>
        cliRun(state, args, { stdio: "inherit", timeout: 24 * 3600_000 }).catch((error) => {
          if (!(error instanceof CommandError)) throw error;
          process.exitCode = 1;
        }),
      );
      return;
    }
    case "watchdog":
      await watchdog(args);
      return;
    case "check": {
      await lockDaemon("shared");
      const state = await readState();
      if (!state) throw new Error("no verify stack here: `up` starts one");
      await recording(() => check(state));
      await writeState(state);
      return;
    }
    case "report":
      await report(args);
      return;
    case "down":
      await lockDaemon("exclusive");
      await down(args);
      return;
    case undefined:
    case "help":
    case "--help":
      say(HELP);
      return;
    default:
      throw new Error(`unknown command ${command}\n${HELP}`);
  }
}

main().catch((error) => {
  process.stderr.write(`verify stack: ${error.message}\n`);
  process.exit(1);
});
